const DAY = 86400000;
const today = new Date();
const isoDate = d => new Date(d).toISOString().slice(0, 10);
const addDays = n => isoDate(new Date(today.getTime() + n * DAY));
const uid = prefix => `${prefix}_${Date.now().toString(36)}${Math.random().toString(36).slice(2, 6)}`;
const escapeHtml = value => String(value ?? "").replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));

const demoData = {
  roots: [
    {id:"r1",name:"AI 교육 1팀",email:"owner-a@example.com",billingDay:12,expiry:addDays(18),capacity:25,status:"운영 중",memo:""},
    {id:"r2",name:"AI 교육 2팀",email:"owner-b@example.com",billingDay:25,expiry:addDays(71),capacity:18,status:"운영 중",memo:""},
    {id:"r3",name:"실습 예비 워크스페이스",email:"owner-c@example.com",billingDay:3,expiry:addDays(9),capacity:12,status:"종료 예정",memo:"갱신 여부 확인"}
  ],
  children: [
    {id:"c1",rootId:"r1",name:"교육 운영 01",email:"member01@example.com",status:"사용 중"},{id:"c2",rootId:"r1",name:"교육 운영 02",email:"member02@example.com",status:"사용 가능"},{id:"c3",rootId:"r1",name:"교육 운영 03",email:"member03@example.com",status:"사용 중"},{id:"c4",rootId:"r2",name:"실습 계정 01",email:"lab01@example.com",status:"사용 가능"},{id:"c5",rootId:"r2",name:"실습 계정 02",email:"lab02@example.com",status:"사용 중"},{id:"c6",rootId:"r3",name:"예비 계정 01",email:"reserve01@example.com",status:"사용 가능"}
  ],
  guests: [
    {id:"g1",name:"김민서",email:"minseo@example.com",organization:"ABC 교육원",rootId:"r1",courseId:"co1",start:addDays(-2),end:addDays(3),removedAt:"",memo:""},
    {id:"g2",name:"박준호",email:"junho@example.com",organization:"XYZ 연구소",rootId:"r2",courseId:"co2",start:addDays(-8),end:addDays(-1),removedAt:"",memo:"제거 확인 필요"},
    {id:"g3",name:"이서윤",email:"seoyun@example.com",organization:"개인",rootId:"r1",courseId:"co3",start:addDays(6),end:addDays(8),removedAt:"",memo:""}
  ],
  courses: [
    {id:"co1",title:"생성형 AI 실무 과정",start:`${addDays(2)}T10:00`,end:`${addDays(2)}T17:00`,required:20,assigned:18,rootId:"r1",manager:"정우진",status:"확정",memo:""},
    {id:"co2",title:"GPT 업무자동화 워크숍",start:`${addDays(6)}T09:30`,end:`${addDays(6)}T16:00`,required:15,assigned:15,rootId:"r2",manager:"한유리",status:"확정",memo:""},
    {id:"co3",title:"프롬프트 디자인 기초",start:`${addDays(8)}T13:00`,end:`${addDays(8)}T18:00`,required:24,assigned:17,rootId:"r1",manager:"강지훈",status:"예정",memo:"추가 좌석 검토"}
  ],
  settings:{ownerUsesSeat:true}
};

let state = loadLocal();
let currentView = "dashboard";
let calendarDate = new Date(today.getFullYear(), today.getMonth(), 1);
let editing = null;

function loadLocal(){try{return JSON.parse(localStorage.getItem("gpt-account-manager-data")) || structuredClone(demoData)}catch{return structuredClone(demoData)}}
function apiUrl(){return localStorage.getItem("gpt-account-manager-api") || window.APP_CONFIG?.appsScriptUrl || ""}
function rootName(id){return state.roots.find(r=>r.id===id)?.name || "미지정"}
function guestStatus(g){if(g.removedAt)return "제거 완료";const d=isoDate(today);if(g.end<d)return "제거 필요";if(g.start>d)return "초대 예정";return "이용 중"}
function statusClass(s){return ["제거 필요","종료","취소"].includes(s)?"danger":["종료 예정","초대 예정","예정"].includes(s)?"warn":["제거 완료","완료"].includes(s)?"neutral":""}
function activeGuests(rootId, date=isoDate(today)){return state.guests.filter(g=>g.rootId===rootId&&!g.removedAt&&g.start<=date&&g.end>=date).length}
function usedSeats(root){return state.children.filter(c=>c.rootId===root.id&&c.status!=="보관"&&c.status!=="사용 중지").length+activeGuests(root.id)+(state.settings.ownerUsesSeat?1:0)}
function freeSeats(root){return Math.max(0,Number(root.capacity)-usedSeats(root))}
function courseLevel(c){const missing=Number(c.required)-Number(c.assigned);return missing<=0?"ok":Number(c.assigned)>0?"warn":"danger"}
function fmtDate(d){return new Intl.DateTimeFormat("ko-KR",{month:"short",day:"numeric",weekday:"short"}).format(new Date(d))}
function fmtDateTime(d){return new Intl.DateTimeFormat("ko-KR",{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(d))}
function showToast(message){const el=document.querySelector("#toast");el.textContent=message;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2200)}

async function loadRemote(){if(!apiUrl())return renderAll();setSync("loading","데이터 불러오는 중");try{const res=await fetch(`${apiUrl()}?action=all&t=${Date.now()}`);if(!res.ok)throw new Error();const json=await res.json();if(json.ok===false)throw new Error(json.error);state=json.data;normalize();localStorage.setItem("gpt-account-manager-data",JSON.stringify(state));setSync("connected","Google Sheets 연결됨");renderAll()}catch(e){setSync("error","연결 오류 · 로컬 데이터");showToast("Sheets 연결에 실패해 로컬 데이터를 표시합니다.");renderAll()}}
async function persist(){normalize();localStorage.setItem("gpt-account-manager-data",JSON.stringify(state));renderAll();if(!apiUrl())return;setSync("loading","저장 중");try{const res=await fetch(apiUrl(),{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action:"saveAll",data:state})});const json=await res.json();if(json.ok===false)throw new Error(json.error);setSync("connected","Google Sheets 연결됨");showToast("Google Sheets에 저장했습니다.")}catch(e){setSync("error","동기화 실패 · 로컬 저장됨");showToast("로컬에는 저장했지만 Sheets 동기화에 실패했습니다.")}}
function normalize(){state.roots ||= [];state.children ||= [];state.guests ||= [];state.courses ||= [];state.settings ||= {ownerUsesSeat:true}}
function setSync(type,label){document.querySelector("#syncLabel").textContent=label;document.querySelector("#syncDot").className=`sync-dot ${type==="connected"?"connected":""}`}

function renderAll(){normalize();renderDashboard();renderAccounts();renderGuests();renderCalendar();renderSettings()}
function renderDashboard(){
  const activeRoots=state.roots.filter(r=>r.status==="운영 중"||r.status==="종료 예정");
  const totalCapacity=activeRoots.reduce((a,r)=>a+Number(r.capacity),0), used=activeRoots.reduce((a,r)=>a+usedSeats(r),0);
  const activeGuestCount=state.guests.filter(g=>guestStatus(g)==="이용 중").length;
  const maxShortage=Math.max(0,...state.courses.filter(c=>new Date(c.start)>=today&&new Date(c.start)<=new Date(today.getTime()+30*DAY)).map(c=>Number(c.required)-Number(c.assigned)));
  document.querySelector("#heroShortage").textContent=maxShortage;
  const cards=[['워크스페이스',activeRoots.length,'운영 중','▦'],['전체 좌석',totalCapacity,`${used}석 사용 중`,'◫'],['여유 좌석',Math.max(0,totalCapacity-used),'현재 배정 가능','↗'],['이용 중 게스트',activeGuestCount,'기간제 멤버','♙']];
  document.querySelector("#metrics").innerHTML=cards.map(x=>`<article class="metric"><div class="metric-head"><span>${x[0]}</span><i class="metric-icon">${x[3]}</i></div><strong>${x[1]}</strong><small>${x[2]}</small></article>`).join("");
  document.querySelector("#capacityList").innerHTML=activeRoots.map(r=>{const used=usedSeats(r),pct=Math.min(100,Math.round(used/Number(r.capacity)*100));return `<div class="capacity-row"><div class="capacity-name"><b>${escapeHtml(r.name)}</b><small>${escapeHtml(r.email)}</small></div><div class="bar"><i class="${pct>=85?'high':''}" style="width:${pct}%"></i></div><div class="capacity-num"><b>${used}</b> / ${r.capacity}</div></div>`}).join("")||`<div class="empty">등록된 워크스페이스가 없습니다.</div>`;
  const actions=[];state.guests.filter(g=>guestStatus(g)==="제거 필요").forEach(g=>actions.push({danger:true,title:`${g.name} 제거 필요`,sub:`${rootName(g.rootId)} · ${g.end} 종료`}));state.roots.filter(r=>r.status!=="종료"&&(new Date(r.expiry)-today)/DAY<=30).forEach(r=>actions.push({danger:false,title:`${r.name} 만료 임박`,sub:`${r.expiry} · ${Math.max(0,Math.ceil((new Date(r.expiry)-today)/DAY))}일 남음`}));state.courses.filter(c=>new Date(c.start)>=today&&Number(c.required)>Number(c.assigned)).forEach(c=>actions.push({danger:true,title:`${c.title} ${Number(c.required)-Number(c.assigned)}석 부족`,sub:fmtDateTime(c.start)}));
  document.querySelector("#actionCount").textContent=actions.length;document.querySelector("#actionList").innerHTML=actions.slice(0,5).map(a=>`<div class="action-item ${a.danger?'danger':''}"><i></i><div><b>${escapeHtml(a.title)}</b><small>${escapeHtml(a.sub)}</small></div></div>`).join("")||`<div class="empty">지금 처리할 일이 없습니다.</div>`;
  document.querySelector("#upcomingCourses").innerHTML=state.courses.filter(c=>new Date(c.start)>=new Date(today.toDateString())&&c.status!=="취소").sort((a,b)=>new Date(a.start)-new Date(b.start)).slice(0,5).map(c=>`<tr><td>${fmtDateTime(c.start)}</td><td><b>${escapeHtml(c.title)}</b><small>${escapeHtml(c.manager||'담당자 미정')}</small></td><td>${c.required}</td><td>${c.assigned}</td><td><span class="status ${statusClass(courseLevel(c)==='ok'?'확정':'예정')}">${courseLevel(c)==='ok'?'충족':`${Number(c.required)-Number(c.assigned)}석 부족`}</span></td></tr>`).join("")||`<tr><td colspan="5" class="empty">예정된 강의가 없습니다.</td></tr>`;
}
function renderAccounts(){const q=document.querySelector("#accountSearch").value.toLowerCase(),f=document.querySelector("#accountFilter").value;const rows=state.roots.filter(r=>(f==="all"||r.status===f)&&[r.name,r.email,...state.children.filter(c=>c.rootId===r.id).flatMap(c=>[c.name,c.email])].join(' ').toLowerCase().includes(q));document.querySelector("#workspaceGrid").innerHTML=rows.map(r=>{const children=state.children.filter(c=>c.rootId===r.id&&c.status!=="보관");return `<article class="workspace-card ${r.status==='종료'?'archived':''}"><div class="workspace-head"><div class="workspace-symbol">${escapeHtml(r.name.slice(0,1))}</div><div><h3>${escapeHtml(r.name)}</h3><p>${escapeHtml(r.email)}</p></div><span class="status ${statusClass(r.status)}">${r.status}</span></div><div class="workspace-stats"><div><small>총 좌석</small><b>${r.capacity}</b></div><div><small>사용</small><b>${usedSeats(r)}</b></div><div><small>여유</small><b>${freeSeats(r)}</b></div></div><div class="member-list">${children.map(c=>`<div class="member"><span class="avatar">${escapeHtml(c.name.slice(-2))}</span><div><b>${escapeHtml(c.name)}</b><small>${escapeHtml(c.email)}</small></div><span class="status ${statusClass(c.status)}">${c.status}</span></div>`).join('')||'<div class="empty">상시 멤버가 없습니다.</div>'}</div><div class="workspace-actions"><button class="mini-button" data-add-child="${r.id}">+ 상시 멤버</button><button class="mini-button" data-edit-root="${r.id}">워크스페이스 수정</button></div></article>`}).join('')||'<div class="empty">검색 결과가 없습니다.</div>'}
function renderGuests(){const q=document.querySelector("#guestSearch").value.toLowerCase(),f=document.querySelector("#guestFilter").value;const rows=state.guests.filter(g=>(f==='all'||guestStatus(g)===f)&&[g.name,g.email,g.organization].join(' ').toLowerCase().includes(q));document.querySelector("#guestTable").innerHTML=rows.map(g=>`<tr><td><b>${escapeHtml(g.name)}</b><small>${escapeHtml(g.email)}</small></td><td>${escapeHtml(g.organization||'-')}</td><td>${escapeHtml(rootName(g.rootId))}</td><td>${g.start} → ${g.end}</td><td><span class="status ${statusClass(guestStatus(g))}">${guestStatus(g)}</span></td><td><div class="row-actions">${guestStatus(g)==='제거 필요'?`<button class="mini-button" data-remove-guest="${g.id}">제거 완료</button>`:''}<button class="mini-button" data-edit-guest="${g.id}">수정</button></div></td></tr>`).join('')||'<tr><td colspan="6" class="empty">등록된 기간제 멤버가 없습니다.</td></tr>'}
function renderCalendar(){const y=calendarDate.getFullYear(),m=calendarDate.getMonth();document.querySelector("#monthLabel").textContent=`${y}년 ${m+1}월`;const first=new Date(y,m,1),start=new Date(y,m,1-first.getDay());let html='';for(let i=0;i<42;i++){const d=new Date(start.getTime()+i*DAY),key=isoDate(d),events=state.courses.filter(c=>c.start.slice(0,10)===key);html+=`<div class="day ${d.getMonth()!==m?'muted':''} ${key===isoDate(today)?'today':''}"><span class="day-number">${d.getDate()}</span>${events.map(c=>`<div class="course-chip ${courseLevel(c)}" title="${escapeHtml(c.title)}"><b>${escapeHtml(c.title)}</b>${c.start.slice(11,16)} · ${c.assigned}/${c.required}</div>`).join('')}</div>`}document.querySelector("#calendar").innerHTML=html}
function renderSettings(){document.querySelector("#apiUrlInput").value=apiUrl();document.querySelector("#ownerSeatToggle").checked=!!state.settings.ownerUsesSeat;document.querySelector("#connectionHint").textContent=apiUrl()?"URL이 저장되어 있습니다. 새로고침 시 Sheets 데이터를 불러옵니다.":"현재 예시 또는 브라우저 저장 데이터를 사용 중입니다."}

const field=(name,label,type='text',value='',extra='',full=false)=>`<label class="${full?'full':''}">${label}<${type==='textarea'?'textarea':'input'} name="${name}" ${type!=='textarea'?`type="${type}"`:''} value="${type==='textarea'?'':escapeHtml(value)}" ${extra}>${type==='textarea'?escapeHtml(value):''}</${type==='textarea'?'textarea':'input'}></label>`;
const selectField=(name,label,options,value,full=false)=>`<label class="${full?'full':''}">${label}<select name="${name}">${options.map(o=>`<option ${o===value?'selected':''}>${o}</option>`).join('')}</select></label>`;
const rootSelect=(value)=>`<label>소속 워크스페이스<select name="rootId" required>${state.roots.filter(r=>r.status!=="종료").map(r=>`<option value="${r.id}" ${r.id===value?'selected':''}>${escapeHtml(r.name)}</option>`).join('')}</select></label>`;
function openEditor(type,id=null,parentId=null){editing={type,id,parentId};let item,title,fields;if(type==='root'){item=state.roots.find(x=>x.id===id)||{};title=id?'워크스페이스 수정':'워크스페이스 추가';fields=field('name','워크스페이스명','text',item.name,'required')+field('email','소유자 이메일','email',item.email,'required')+field('billingDay','결제 기준일','number',item.billingDay||1,'min="1" max="31" required')+field('expiry','만료일','date',item.expiry||addDays(365),'required')+field('capacity','총 좌석 수','number',item.capacity||10,'min="1" required')+selectField('status','상태',['운영 중','종료 예정','종료','보관'],item.status||'운영 중')+field('memo','메모','textarea',item.memo,'',true)}else if(type==='child'){title='상시 멤버 추가';fields=rootSelect(parentId)+field('name','멤버명','text','','required')+field('email','이메일','email','','required')+selectField('status','상태',['사용 가능','사용 중','사용 예정','사용 중지','보관'],'사용 가능')+field('memo','메모','textarea','','',true)}else if(type==='guest'){item=state.guests.find(x=>x.id===id)||{};title=id?'기간제 멤버 수정':'기간제 멤버 추가';fields=field('name','이름','text',item.name,'required')+field('email','이메일','email',item.email,'required')+field('organization','소속','text',item.organization)+rootSelect(item.rootId)+field('start','초대 시작일','date',item.start||isoDate(today),'required')+field('end','초대 종료일','date',item.end||addDays(1),'required')+field('memo','메모','textarea',item.memo,'',true)}else{title='강의 일정 추가';fields=field('title','강의명','text','','required')+rootSelect('')+field('start','시작 일시','datetime-local',`${addDays(1)}T10:00`,'required')+field('end','종료 일시','datetime-local',`${addDays(1)}T17:00`,'required')+field('required','필요 좌석','number',10,'min="1" required')+field('assigned','배정 좌석','number',0,'min="0" required')+field('manager','담당자','text','')+selectField('status','상태',['예정','확정','진행','완료','취소'],'예정')+field('memo','메모','textarea','','',true)}document.querySelector("#dialogTitle").textContent=title;document.querySelector("#formFields").innerHTML=fields;document.querySelector("#editorDialog").showModal()}
function saveEditor(form){const v=Object.fromEntries(new FormData(form));if(editing.type==='root'){const item={id:editing.id||uid('r'),name:v.name,email:v.email,billingDay:Number(v.billingDay),expiry:v.expiry,capacity:Number(v.capacity),status:v.status,memo:v.memo};editing.id?Object.assign(state.roots.find(x=>x.id===editing.id),item):state.roots.push(item)}else if(editing.type==='child'){state.children.push({id:uid('c'),rootId:v.rootId,name:v.name,email:v.email,status:v.status,memo:v.memo})}else if(editing.type==='guest'){if(v.end<v.start){showToast('종료일은 시작일보다 빠를 수 없습니다.');return false}const item={id:editing.id||uid('g'),name:v.name,email:v.email,organization:v.organization,rootId:v.rootId,courseId:'',start:v.start,end:v.end,removedAt:editing.id?state.guests.find(x=>x.id===editing.id).removedAt:'',memo:v.memo};editing.id?Object.assign(state.guests.find(x=>x.id===editing.id),item):state.guests.push(item)}else{if(v.end<v.start){showToast('종료 일시는 시작 일시보다 빠를 수 없습니다.');return false}state.courses.push({id:uid('co'),title:v.title,rootId:v.rootId,start:v.start,end:v.end,required:Number(v.required),assigned:Number(v.assigned),manager:v.manager,status:v.status,memo:v.memo})}persist();return true}

function switchView(view){currentView=view;document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===`${view}View`));document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===view));const titles={dashboard:'운영 현황',accounts:'워크스페이스 관리',courses:'강의 일정',guests:'기간제 멤버',settings:'연결 설정'};document.querySelector('#pageTitle').textContent=titles[view];document.querySelector('.sidebar').classList.remove('open')}
document.addEventListener('click',e=>{const t=e.target.closest('button');if(!t)return;if(t.dataset.view)switchView(t.dataset.view);if(t.dataset.go)switchView(t.dataset.go);if(t.dataset.add)openEditor(t.dataset.add);if(t.dataset.addChild)openEditor('child',null,t.dataset.addChild);if(t.dataset.editRoot)openEditor('root',t.dataset.editRoot);if(t.dataset.editGuest)openEditor('guest',t.dataset.editGuest);if(t.dataset.removeGuest){const g=state.guests.find(x=>x.id===t.dataset.removeGuest);g.removedAt=isoDate(today);persist()}if(t.id==='quickAddButton')openEditor(currentView==='accounts'?'root':currentView==='courses'?'course':currentView==='guests'?'guest':'course');if(t.id==='menuButton')document.querySelector('.sidebar').classList.toggle('open');if(t.id==='prevMonth'){calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth()-1,1);renderCalendar()}if(t.id==='nextMonth'){calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth()+1,1);renderCalendar()}if(t.id==='refreshButton')loadRemote();if(t.id==='saveSettings'){const url=document.querySelector('#apiUrlInput').value.trim();if(url&&!/^https:\/\/script\.google\.com\//.test(url)){showToast('Apps Script 웹 앱 URL을 확인해 주세요.');return}url?localStorage.setItem('gpt-account-manager-api',url):localStorage.removeItem('gpt-account-manager-api');showToast('연결 설정을 저장했습니다.');loadRemote()}if(t.id==='disconnectButton'){localStorage.removeItem('gpt-account-manager-api');document.querySelector('#apiUrlInput').value='';setSync('','로컬 데이터');renderSettings();showToast('Sheets 연결을 해제했습니다.')}});
document.querySelector('#editorForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();if(saveEditor(e.currentTarget))document.querySelector('#editorDialog').close()});
['accountSearch','accountFilter'].forEach(id=>document.querySelector(`#${id}`).addEventListener('input',renderAccounts));['guestSearch','guestFilter'].forEach(id=>document.querySelector(`#${id}`).addEventListener('input',renderGuests));document.querySelector('#ownerSeatToggle').addEventListener('change',e=>{state.settings.ownerUsesSeat=e.target.checked;persist()});
document.querySelector('#todayLabel').textContent=new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'long',day:'numeric',weekday:'long'}).format(today);if(apiUrl())setSync('connected','Google Sheets 연결됨');renderAll();loadRemote();
